---
linters:
  enable-all: true
  disable:
  - wsl
  - err113
  - lll
  - godot
  - nlreturn
  - godox
  - execinquery # WARN The linter 'execinquery' is deprecated (since v1.58.0) due to: The repository of the linter has been archived by the owner.  
  - gomnd # WARN The linter 'gomnd' is deprecated (since v1.58.0) due to: The linter has been renamed. Replaced by mnd. 
  - varnamelen
  - exhaustruct
  - depguard
  # TODO
  - wrapcheck
  - ireturn
  - inamedparam
  - cyclop
  - gci
  - revive
